/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2020-02-11 12:03:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.Article;
import java.util.ArrayList;
import model.Client;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.Client");
    _jspx_imports_classes.add("model.Article");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>FDP - Food De Paris</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/open-iconic-bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/aos.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/ionicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap-datepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/jquery.timepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/flaticon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/icomoon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"goto-here\">\r\n");
      out.write("\t<nav\r\n");
      out.write("\t\tclass=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light\"\r\n");
      out.write("\t\tid=\"ftco-navbar\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"index.jsp\">FDP - Food De Paris</a>\r\n");
      out.write("\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\tdata-target=\"#ftco-nav\" aria-controls=\"ftco-nav\"\r\n");
      out.write("\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t<span class=\"oi oi-menu\"></span> Menu\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t\t<li class=\"nav-item active\"><a href=\"index.jsp\"\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link\">Home</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item active\"><a href=\"login.jsp\"\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link\">Login</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item cta cta-colored\"><a href=\"cart.jsp\"\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link\"><span class=\"icon-shopping_cart\"></span>[");
 int num = (int) application.getAttribute("numberArticle"); 
					out.print(num); 
      out.write("]</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<section id=\"home-section\" class=\"hero\">\r\n");
      out.write("\t<div class=\"home-slider owl-carousel\">\r\n");
      out.write("\t\t<div class=\"slider-item\"\r\n");
      out.write("\t\t\tstyle=\"background-image: url(images/bg_1.jpg);\">\r\n");
      out.write("\t\t\t<div class=\"overlay\"></div>\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tclass=\"row slider-text justify-content-center align-items-center\"\r\n");
      out.write("\t\t\t\t\tdata-scrollax-parent=\"true\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12 ftco-animate text-center\">\r\n");
      out.write("\t\t\t\t\t\t<h1 class=\"mb-2\">We serve Fresh Vegestables &amp; Fruits</h1>\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"subheading mb-4\">We deliver organic vegetables\r\n");
      out.write("\t\t\t\t\t\t\t&amp; fruits</h2>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#shop\" class=\"btn btn-primary\">View Details</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"slider-item\"\r\n");
      out.write("\t\t\tstyle=\"background-image: url(images/bg_2.jpg);\">\r\n");
      out.write("\t\t\t<div class=\"overlay\"></div>\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tclass=\"row slider-text justify-content-center align-items-center\"\r\n");
      out.write("\t\t\t\t\tdata-scrollax-parent=\"true\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-12 ftco-animate text-center\">\r\n");
      out.write("\t\t\t\t\t\t<h1 class=\"mb-2\">100% Fresh &amp; Organic Foods</h1>\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"subheading mb-4\">We deliver organic vegetables\r\n");
      out.write("\t\t\t\t\t\t\t&amp; fruits</h2>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#shop\" class=\"btn btn-primary\">View Details</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"ftco-section\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row no-gutters ftco-services\">\r\n");
      out.write("\t\t\t<div\r\n");
      out.write("\t\t\t\tclass=\"col-md-3 text-center d-flex align-self-stretch ftco-animate\">\r\n");
      out.write("\t\t\t\t<div class=\"media block-6 services mb-md-0 mb-4\">\r\n");
      out.write("\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon bg-color-1 active d-flex justify-content-center align-items-center mb-2\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"flaticon-shipped\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"heading\">Free Shipping</h3>\r\n");
      out.write("\t\t\t\t\t\t<span>On order over $100</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div\r\n");
      out.write("\t\t\t\tclass=\"col-md-3 text-center d-flex align-self-stretch ftco-animate\">\r\n");
      out.write("\t\t\t\t<div class=\"media block-6 services mb-md-0 mb-4\">\r\n");
      out.write("\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon bg-color-2 d-flex justify-content-center align-items-center mb-2\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"flaticon-diet\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"heading\">Always Fresh</h3>\r\n");
      out.write("\t\t\t\t\t\t<span>Product well package</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div\r\n");
      out.write("\t\t\t\tclass=\"col-md-3 text-center d-flex align-self-stretch ftco-animate\">\r\n");
      out.write("\t\t\t\t<div class=\"media block-6 services mb-md-0 mb-4\">\r\n");
      out.write("\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon bg-color-3 d-flex justify-content-center align-items-center mb-2\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"flaticon-award\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"heading\">Superior Quality</h3>\r\n");
      out.write("\t\t\t\t\t\t<span>Quality Products</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div\r\n");
      out.write("\t\t\t\tclass=\"col-md-3 text-center d-flex align-self-stretch ftco-animate\">\r\n");
      out.write("\t\t\t\t<div class=\"media block-6 services mb-md-0 mb-4\">\r\n");
      out.write("\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon bg-color-4 d-flex justify-content-center align-items-center mb-2\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"flaticon-customer-service\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"heading\">Support</h3>\r\n");
      out.write("\t\t\t\t\t\t<span>24/7 Support</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"ftco-section ftco-category ftco-no-pt\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6 order-md-last align-items-stretch d-flex\">\r\n");
      out.write("\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"category-wrap-2 ftco-animate img align-self-stretch d-flex\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"background-image: url(images/category.jpg);\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2>Vegetables</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Protect the health of every home</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"category-wrap ftco-animate img mb-4 d-flex align-items-end\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"background-image: url(images/category-1.jpg);\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text px-3 py-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">Fruits</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"category-wrap ftco-animate img d-flex align-items-end\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"background-image: url(images/category-2.jpg);\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text px-3 py-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">Vegetables</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tclass=\"category-wrap ftco-animate img mb-4 d-flex align-items-end\"\r\n");
      out.write("\t\t\t\t\tstyle=\"background-image: url(images/category-3.jpg);\">\r\n");
      out.write("\t\t\t\t\t<div class=\"text px-3 py-1\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">Juices</a>\r\n");
      out.write("\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"category-wrap ftco-animate img d-flex align-items-end\"\r\n");
      out.write("\t\t\t\t\tstyle=\"background-image: url(images/category-4.jpg);\">\r\n");
      out.write("\t\t\t\t\t<div class=\"text px-3 py-1\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">Dried</a>\r\n");
      out.write("\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"ftco-section\" id=\"shop\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row justify-content-center mb-3 pb-3\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12 heading-section text-center ftco-animate\">\r\n");
      out.write("\t\t\t\t<span class=\"subheading\">Featured Products</span>\r\n");
      out.write("\t\t\t\t<h2 class=\"mb-4\">Our Products</h2>\r\n");
      out.write("\t\t\t\t<p>Far far away, behind the word mountains, far from the\r\n");
      out.write("\t\t\t\t\tcountries Vokalia and Consonantia</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-6 col-lg-3 ftco-animate\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<form method=\"post\" action=\"ServletAddPanier\" id=\"product1\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"img-prod\"><img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"images/product-1.jpg\" alt=\"Colorlib Template\"> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"status\">30%</span>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"overlay\"></div> </a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text py-3 pb-4 px-3 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Bell Pepper</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pricing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"price\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"mr-2 price-dc\">$120.00</span><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"price-sale\">$80.00</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"id\" value=\"1\" hidden>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bottom-area d-flex px-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"m-auto d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"product-single.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"add-to-cart d-flex justify-content-center align-items-center text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><i class=\"ion-ios-menu\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a> <a onclick=\"SubmitFruit1()\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"buy-now d-flex justify-content-center align-items-center mx-1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"cursor: pointer;\"> <span><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"ion-ios-cart\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\tfunction SubmitFruit1() {\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"product1\").submit();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-6 col-lg-3 ftco-animate\">\r\n");
      out.write("\t\t\t\t<form method=\"post\" action=\"ServletAddPanier\" id=\"product2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"img-prod\"><img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"images/product-2.jpg\" alt=\"Colorlib Template\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"overlay\"></div> </a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text py-3 pb-4 px-3 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Strawberry</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pricing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"price\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>$120.00</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"id\" value=\"2\" hidden>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bottom-area d-flex px-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"m-auto d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"product-single.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"add-to-cart d-flex justify-content-center align-items-center text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><i class=\"ion-ios-menu\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a> <a onclick=\"SubmitFruit2()\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"buy-now d-flex justify-content-center align-items-center mx-1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"cursor: pointer;\"> <span><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"ion-ios-cart\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\tfunction SubmitFruit2() {\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"product2\").submit();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-6 col-lg-3 ftco-animate\">\r\n");
      out.write("\t\t\t\t<form method=\"post\" action=\"ServletAddPanier\" id=\"product3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"img-prod\"><img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"images/product-3.jpg\" alt=\"Colorlib Template\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"overlay\"></div> </a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text py-3 pb-4 px-3 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Green Beans</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pricing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"price\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>$120.00</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"id\" value=\"3\" hidden>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bottom-area d-flex px-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"m-auto d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"product-single.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"add-to-cart d-flex justify-content-center align-items-center text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><i class=\"ion-ios-menu\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a><a onclick=\"SubmitFruit3()\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"buy-now d-flex justify-content-center align-items-center mx-1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"cursor: pointer;\"> <span><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"ion-ios-cart\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\tfunction SubmitFruit3() {\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"product3\").submit();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-6 col-lg-3 ftco-animate\">\r\n");
      out.write("\t\t\t\t<form method=\"post\" action=\"ServletAddPanier\" id=\"product4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"img-prod\"><img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"images/product-4.jpg\" alt=\"Colorlib Template\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"overlay\"></div> </a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text py-3 pb-4 px-3 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Purple Cabbage</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pricing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"price\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>$120.00</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"id\" value=\"4\" hidden>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bottom-area d-flex px-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"m-auto d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"product-single.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"add-to-cart d-flex justify-content-center align-items-center text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><i class=\"ion-ios-menu\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a><a onclick=\"SubmitFruit4()\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"buy-now d-flex justify-content-center align-items-center mx-1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"cursor: pointer;\"> <span><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"ion-ios-cart\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\tfunction SubmitFruit4() {\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"product4\").submit();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-6 col-lg-3 ftco-animate\">\r\n");
      out.write("\t\t\t\t<form method=\"post\" action=\"ServletAddPanier\" id=\"product5\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"img-prod\"><img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"images/product-5.jpg\" alt=\"Colorlib Template\"> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"status\">30%</span>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"overlay\"></div> </a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text py-3 pb-4 px-3 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Tomatoe</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pricing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"price\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"mr-2 price-dc\">$120.00</span><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"price-sale\">$80.00</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"id\" value=\"5\" hidden>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bottom-area d-flex px-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"m-auto d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"product-single.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"add-to-cart d-flex justify-content-center align-items-center text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><i class=\"ion-ios-menu\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a> <a onclick=\"SubmitFruit5()\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"buy-now d-flex justify-content-center align-items-center mx-1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"cursor: pointer;\"> <span><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"ion-ios-cart\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\tfunction SubmitFruit5() {\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"product5\").submit();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-6 col-lg-3 ftco-animate\">\r\n");
      out.write("\t\t\t\t<form method=\"post\" action=\"ServletAddPanier\" id=\"product6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"img-prod\"><img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"images/product-6.jpg\" alt=\"Colorlib Template\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"overlay\"></div> </a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text py-3 pb-4 px-3 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Brocolli</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pricing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"price\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>$120.00</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"id\" value=\"6\" hidden>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bottom-area d-flex px-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"m-auto d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"product-single.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"add-to-cart d-flex justify-content-center align-items-center text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><i class=\"ion-ios-menu\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a> <a onclick=\"SubmitFruit6()\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"buy-now d-flex justify-content-center align-items-center mx-1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"cursor: pointer;\"> <span><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"ion-ios-cart\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\tfunction SubmitFruit6() {\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"product6\").submit();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-6 col-lg-3 ftco-animate\">\r\n");
      out.write("\t\t\t\t<form method=\"post\" action=\"ServletAddPanier\" id=\"product7\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"img-prod\"><img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"images/product-7.jpg\" alt=\"Colorlib Template\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"overlay\"></div> </a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text py-3 pb-4 px-3 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Carrots</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pricing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"price\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>$120.00</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"id\" value=\"7\" hidden>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bottom-area d-flex px-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"m-auto d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"product-single.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"add-to-cart d-flex justify-content-center align-items-center text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><i class=\"ion-ios-menu\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a> <a onclick=\"SubmitFruit7()\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"buy-now d-flex justify-content-center align-items-center mx-1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"cursor: pointer;\"> <span><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"ion-ios-cart\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\tfunction SubmitFruit7() {\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"product7\").submit();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-6 col-lg-3 ftco-animate\">\r\n");
      out.write("\t\t\t\t<form method=\"post\" action=\"ServletAddPanier\" id=\"product8\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"img-prod\"><img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"images/product-8.jpg\" alt=\"Colorlib Template\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"overlay\"></div> </a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text py-3 pb-4 px-3 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Fruit Juice</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pricing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"price\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>$120.00</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"id\" value=\"8\" hidden>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bottom-area d-flex px-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"m-auto d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"product-single.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"add-to-cart d-flex justify-content-center align-items-center text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><i class=\"ion-ios-menu\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a> <a onclick=\"SubmitFruit8()\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"buy-now d-flex justify-content-center align-items-center mx-1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"cursor: pointer;\"> <span><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"ion-ios-cart\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\tfunction SubmitFruit8() {\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"product8\").submit();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- loader -->\r\n");
      out.write("\t<div id=\"ftco-loader\" class=\"show fullscreen\">\r\n");
      out.write("\t\t<svg class=\"circular\" width=\"48px\" height=\"48px\"> <circle\r\n");
      out.write("\t\t\tclass=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\"\r\n");
      out.write("\t\t\tstroke=\"#eeeeee\" /> <circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\"\r\n");
      out.write("\t\t\tfill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\" /></svg>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/popper.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.stellar.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/aos.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("\t<script src=\"js/scrollax.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
