/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2020-02-11 14:42:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class product_002dsingle_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>FDP - Food De Paris</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/open-iconic-bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/aos.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/ionicons.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap-datepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/jquery.timepicker.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/flaticon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/icomoon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"goto-here\">\r\n");
      out.write("\r\n");
      out.write("\t<nav\r\n");
      out.write("\t\tclass=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light\"\r\n");
      out.write("\t\tid=\"ftco-navbar\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"index.jsp\">Vegefoods</a>\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\tdata-target=\"#ftco-nav\" aria-controls=\"ftco-nav\"\r\n");
      out.write("\t\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t<span class=\"oi oi-menu\"></span> Menu\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item active\"><a href=\"index.jsp\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item active\"><a href=\"login.jsp\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link\">Login</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item cta cta-colored\"><a href=\"cart.jsp\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link\"><span class=\"icon-shopping_cart\"></span>[");
 int num = (int) application.getAttribute("numberArticle"); 
					out.print(num); 
      out.write("]</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<!-- END nav -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"hero-wrap hero-bread\"\r\n");
      out.write("\t\tstyle=\"background-image: url('images/bg_1.jpg');\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div\r\n");
      out.write("\t\t\t\tclass=\"row no-gutters slider-text align-items-center justify-content-center\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-9 ftco-animate text-center\">\r\n");
      out.write("\t\t\t\t\t<p class=\"breadcrumbs\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"mr-2\"><a href=\"index.jsp\">Home</a></span> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"mr-2\"><a href=\"index.jsp\">Product</a></span> <span>Product\r\n");
      out.write("\t\t\t\t\t\t\tSingle</span>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<h1 class=\"mb-0 bread\">Product Single</h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"ftco-section\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6 mb-5 ftco-animate\">\r\n");
      out.write("\t\t\t\t\t<a href=\"images/product-1.jpg\" class=\"image-popup\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"images/product-1.jpg\" class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Colorlib Template\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6 product-details pl-md-5 ftco-animate\">\r\n");
      out.write("\t\t\t\t\t<h3>Bell Pepper</h3>\r\n");
      out.write("\t\t\t\t\t<div class=\"rating d-flex\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-left mr-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"mr-2\">5.0</a> <a href=\"#\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"ion-ios-star-outline\"></span></a> <a href=\"#\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"ion-ios-star-outline\"></span></a> <a href=\"#\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"ion-ios-star-outline\"></span></a> <a href=\"#\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"ion-ios-star-outline\"></span></a> <a href=\"#\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"ion-ios-star-outline\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-left mr-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"mr-2\" style=\"color: #000;\">100 <span\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"color: #bbb;\">Rating</span></a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-left\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"mr-2\" style=\"color: #000;\">500 <span\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"color: #bbb;\">Sold</span></a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<p class=\"price\">\r\n");
      out.write("\t\t\t\t\t\t<span>$120.00</span>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<p>A small river named Duden flows by their place and supplies\r\n");
      out.write("\t\t\t\t\t\tit with the necessary regelialia. It is a paradisematic country,\r\n");
      out.write("\t\t\t\t\t\tin which roasted parts of sentences fly into your mouth. Text\r\n");
      out.write("\t\t\t\t\t\tshould turn around and return to its own, safe country. But\r\n");
      out.write("\t\t\t\t\t\tnothing the copy said could convince her and so it didnât take\r\n");
      out.write("\t\t\t\t\t\tlong until.</p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"ftco-section\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row justify-content-center mb-3 pb-3\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12 heading-section text-center ftco-animate\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"mb-4\">Related Products</h2>\r\n");
      out.write("\t\t\t\t\t<p>Far far away, behind the word mountains, far from the\r\n");
      out.write("\t\t\t\t\t\tcountries Vokalia and Consonantia</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 col-lg-3 ftco-animate\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"img-prod\"><img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"images/product-1.jpg\" alt=\"Colorlib Template\"> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"status\">30%</span>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"overlay\"></div> </a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text py-3 pb-4 px-3 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Bell Pepper</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pricing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"price\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"mr-2 price-dc\">$120.00</span><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"price-sale\">$80.00</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bottom-area d-flex px-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"m-auto d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"product-single.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"add-to-cart d-flex justify-content-center align-items-center text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><i class=\"ion-ios-menu\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"buy-now d-flex justify-content-center align-items-center mx-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><i class=\"ion-ios-cart\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a> \r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 col-lg-3 ftco-animate\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"img-prod\"><img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"images/product-2.jpg\" alt=\"Colorlib Template\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"overlay\"></div> </a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text py-3 pb-4 px-3 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Strawberry</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pricing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"price\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>$120.00</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bottom-area d-flex px-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"m-auto d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"add-to-cart d-flex justify-content-center align-items-center text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><i class=\"ion-ios-menu\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"buy-now d-flex justify-content-center align-items-center mx-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><i class=\"ion-ios-cart\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a> \r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 col-lg-3 ftco-animate\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"img-prod\"><img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"images/product-3.jpg\" alt=\"Colorlib Template\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"overlay\"></div> </a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text py-3 pb-4 px-3 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Green Beans</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pricing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"price\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>$120.00</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bottom-area d-flex px-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"m-auto d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"add-to-cart d-flex justify-content-center align-items-center text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><i class=\"ion-ios-menu\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"buy-now d-flex justify-content-center align-items-center mx-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><i class=\"ion-ios-cart\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 col-lg-3 ftco-animate\">\r\n");
      out.write("\t\t\t\t\t<div class=\"product\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"img-prod\"><img class=\"img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"images/product-4.jpg\" alt=\"Colorlib Template\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"overlay\"></div> </a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text py-3 pb-4 px-3 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">Purple Cabbage</a>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pricing\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"price\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>$120.00</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bottom-area d-flex px-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"m-auto d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"add-to-cart d-flex justify-content-center align-items-center text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><i class=\"ion-ios-menu\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"buy-now d-flex justify-content-center align-items-center mx-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><i class=\"ion-ios-cart\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a> \r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- loader -->\r\n");
      out.write("\t<div id=\"ftco-loader\" class=\"show fullscreen\">\r\n");
      out.write("\t\t<svg class=\"circular\" width=\"48px\" height=\"48px\">\r\n");
      out.write("\t\t\t<circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("\t\t\t\tstroke-width=\"4\" stroke=\"#eeeeee\" />\r\n");
      out.write("\t\t\t<circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("\t\t\t\tstroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\" /></svg>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/popper.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.stellar.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/aos.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("\t<script src=\"js/scrollax.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false\"></script>\r\n");
      out.write("\t<script src=\"js/google-map.js\"></script>\r\n");
      out.write("\t<script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar quantitiy = 0;\r\n");
      out.write("\t\t\t$('.quantity-right-plus').click(function(e) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t// Stop acting like a button\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t// Get the field name\r\n");
      out.write("\t\t\t\tvar quantity = parseInt($('#quantity').val());\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t// If is not undefined\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$('#quantity').val(quantity + 1);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t// Increment\r\n");
      out.write("\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t$('.quantity-left-minus').click(function(e) {\r\n");
      out.write("\t\t\t\t// Stop acting like a button\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t// Get the field name\r\n");
      out.write("\t\t\t\tvar quantity = parseInt($('#quantity').val());\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t// If is not undefined\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t// Increment\r\n");
      out.write("\t\t\t\tif (quantity > 0) {\r\n");
      out.write("\t\t\t\t\t$('#quantity').val(quantity - 1);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
